### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [chapkachapka/j-m-synge_short-plays#1]
# Typography

- [x] Accept the change made by `typoogrify` (which is consistent with [8.7.7.5](https://standardebooks.org/manual/1.7.3/8-typography#8.7.7.5)).
- [x] Instead of italicizing titles of short plays (like in the preface of “The Tinker’s Wedding”), use quotation marks per [8.2.11.3](https://standardebooks.org/manual/1.7.3/8-typography#8.2.11.3).
- [x] Change the italics around “De Profudis” back to the quotation marks (though you can use a `<span>` for the Latin if you want. I am pretty sure it is being used here as the title for Psalm 130, which makes the usage more like 8.2.11.3 above.

# Semantics

- [x] Add `<abbr>` to `c.` in the colophon.
- [x] You frequently used this pattern

```
<td>
	<p>
		<i epub:type="z3998:stage-direction">Do something.</i>
	</p>
	<p>Blah blah blah.</p>
</td>
```

when it should be

```
<td><i epub:type="z3998:stage-direction">Do something.</i> Blah blah blah.</td>
```

This way the stage direction and the dialogue will be on the same line.

- [x] Instead of the `<div>` at the end of the “Tinker’s Wedding” preface, use a `<footer>`. You can use the `z3998:signature` semantic for “J. M. S.” (which also needs abbreviation semantics for a personal name). Take a look at the [letter footer](https://standardebooks.org/manual/1.7.3/7-high-level-structural-patterns#7.7.3) CSS.
- [x] `se build --check-only` suggests there is a spurious `td` in “In the Shadow of the Glen.”

# CSS

- [x] Is there some reason you can’t use the [standard CSS](https://standardebooks.org/manual/1.7.3/7-high-level-structural-patterns#7.6.7.4) for the dramatis personae?
- [x] Instead of `page-break-after: always` use `break-after: page`. Also, you can consolidate the two rules into a single rule, e.g.

```
section[epub|type~="preface"],
article > hgroup{
  page-break-after: always;
}
```

I would also extract the page break logic from the dramatis personae style and put it this consolidated rule.

# Metadata

- [x] Short description can simply say `A collection of three short plays by Synge.`
- [x] In the long description, use quotation marks around the titles instead of italics.
- [x] `true` should not be all-caps in `se:is-a-collection`.
- [x] In the metadata and colophon, I think you should use “Judith Boss” over “Judy Boss” (it’s the version of the name I’ve seen more commonly in other Gutenberg texts).

# Other

- [x] Accept the modification of `build-images` to `cover.source.jpg`.
- [x] You seem to have created the repository with “J M Synge” as the author rather than “J. M. Synge.” It seems both are used in different sources, but the version with periods is more consistent with our style and moreover is already used in *The Playboy of the Western World*. We should be consistent and use the period version here. To update the SVGs you will have to create a new ebook skeleton with “J. M. Synge” as the author flag and copy the SVGs from there into your repository.

**Comment by chapkachapka** [comment]
These should all be fixed. See discussion board for suggestion on changing stage direction documentation to avoid confusion.

**Comment by weijia-cheng** [comment]
- [x] `titlepage.svg` still needs to be updated with the new author name.
- [x] `signature` needs to be `z3998:signature`. Also, per lint, the `epub:type` attribute should be applied to the `<p>` with the signature instead of creating a `<span>` whose only purpose is the signature semantics.
- [x] Lint complains that the footer in “The Tinker’s Wedding” is followed by a `<p>`. I would say that the note after the dateline is a `z3998:postscript`. Use the CSS given in [7.7.3.5](https://standardebooks.org/manual/1.7.3/7-high-level-structural-patterns#7.7.3.5) (which will also allow you to change the footer CSS to the standard footer CSS in [7.7.3.2](https://standardebooks.org/manual/1.7.3/7-high-level-structural-patterns#7.7.3.2).
- [x] You only have one footer in the entire text so you don’t need the `#the-tinkers-wedding-preface` in the footer CSS.
- [x] I still see "J M Synge" in several places. Try doing `git grep "J M "`

**Comment by weijia-cheng** [comment]
- [x]  `J. M.` in the Wikipedia link in the colophon should receive semantics.
